// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdswwdkcnrvoqfgizrtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkc3d3ZGtjbnJ2b3FmZ2l6cnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjQ2NDEsImV4cCI6MjA2OTYwMDY0MX0.BdzNxXOCwT8kBF7DCmX1TH0F7iZHG0GR-vL96H44pso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});